<!-------------------------------------------------------- NAVBAR ---------------------------------------------------------------------------------------------->
<nav class="navbar navbar-expand-lg mt-5 bg-white fixed-top">
    <div class="container">
        <a class="navbar-brand fw-semibold" href="#">Tenisito</a>
        <!--Responsive Button-->
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="order-lg-2">
            <a href="/login"><button type="button" class="btn btn-outline-dark">Login</button></a>
        </div>
        <div class="collapse navbar-collapse order-lg-1" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto text-center ">
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#carouselExampleIndicators">Home</a>
                </li>
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#about">Sobre nós</a>
                </li>
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#featured">Destaques</a>
                </li>
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#brands">Marcas</a>
                </li>
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#suport">Suporte</a>
                </li>
                <li class="nav-item px-2 py-2">
                    <a class="nav-link text-uppercase text-dark" href="#">Shop</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<!-------------------------------------------------------- HOME ---------------------------------------------------------------------------------------------->
<section id="carouselExampleIndicators" class="carousel slide mt-5" data-spy="scroll" id="carouselExampleIndicators" style="background-color:#EFEFEF" data-bs-ride="carousel">

    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="bg-dark active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" class="bg-dark" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" class="bg-dark" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="container py-5">
                <div class="row">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="assets/banner_img_01.jpg" alt="">
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-dark fw-semibold">Tenisito</h1>
                            <h3 class="h2">A melhor loja de tenis do mercado</h3>
                            <p class="lh-lg">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            </p>

                            <a href="#"><button type="button"" class=" btn btn-dark w-50">Entrar na Loja</button></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container py-5">
                <div class="row">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="assets/banner_img_01.jpg" alt="">
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-dark fw-semibold">Tenisito</h1>
                            <h3 class="h2">A melhor loja de camisas do mercado</h3>
                            <p class="lh-lg">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            </p>

                            <a href="#"><button type="button"" class=" btn btn-dark w-50">Entrar na Loja</button></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="container py-5">
                <div class="row">
                    <div class="mx-auto col-md-8 col-lg-6 order-lg-last">
                        <img class="img-fluid" src="assets/banner_img_01.jpg" alt="">
                    </div>
                    <div class="col-lg-6 mb-0 d-flex align-items-center">
                        <div class="text-align-left align-self-center">
                            <h1 class="h1 text-dark fw-semibold">Tenisito</h1>
                            <h3 class="h2">A melhor loja de camisas do mercado</h3>
                            <p class="lh-lg">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            </p>

                            <a href="#"><button type="button"" class=" btn btn-dark w-50">Entrar na Loja</button></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Arrows Back and Next-->
    <button class="carousel-control-prev " type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>

</section>


<section class="py-5 mt-5" data-spy="scroll" id="about">
    <div class="container">
        <div class="row py-3">
            <div class="col-lg-6 m-auto text-center">
                <h1 class="h1 text-decoration-underline fw-semibold">Sobre nós</h1>
                <p>
                    Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident.
                </p>
            </div>
            <div class="row">
                <div class="col-md-6 text-center align-self-center" data-aos="fade-right">
                    <img src="assets/about.jpg" width="100%" height="100%" class="img-fluid">
                </div>
                <div class="col-md-6 align-self-center" data-aos="fade-left">
                    <h2 class="fw-semibold">Melhor loja de tenis do mercado</h2>
                    <p class="lh-lg">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
                </div>
            </div>
        </div>
    </div>
</section>



<section class="py-5 mt-5" id="featured" style="background-color: #EFEFEF;">
    <div class="container py-5">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1 text-decoration-underline fw-semibold">Destaques</h1>
                <p>
                    Reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident.
                </p>
            </div>
            <div class="row">
                <div class="col-12 col-md-4 mb-4">
                    <div class="card h-100" data-aos="zoom-out">
                        <a href="#"><img src="assets/destaque_img_01.jpg" class="card-img-top" alt="..."></a>
                        <div class="card-body">
                            <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-muted fa fa-star"></i>
                                    <i class="text-muted fa fa-star"></i>
                                </li>
                                <li class="text-muted text-right">$240.00</li>
                            </ul>
                            <a href="#" class="h2 text-decoration-none text-dark">Camisa Addidas</a>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt in culpa qui officia deserunt.</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4 mb-4">
                    <div class="card h-100" data-aos="zoom-out">
                        <a href="#">
                            <img src="assets/destaque_img_02.png" class="card-img-top" alt="...">
                        </a>
                        <div class="card-body">
                            <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-muted fa fa-star"></i>
                                    <i class="text-muted fa fa-star"></i>
                                </li>
                                <li class="text-muted text-right">$480.00</li>
                            </ul>
                            <a href="#" class="h2 text-decoration-none text-dark">Camisa Nike</a>
                            <p class="card-text">
                                Aenean gravida dignissim finibus. Nullam ipsum diam, posuere vitae pharetra sed, commodo ullamcorper.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4 mb-4">
                    <div class="card h-100" data-aos="zoom-out">
                        <a href="#">
                            <img src="assets/destaque_img_02.png" class="card-img-top" alt="...">
                        </a>
                        <div class="card-body">
                            <ul class="list-unstyled d-flex justify-content-between">
                                <li>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                    <i class="text-warning fa fa-star"></i>
                                </li>
                                <li class="text-muted text-right">$360.00</li>
                            </ul>
                            <a href="#" class="h2 text-decoration-none text-dark">Summer Addides Shoes</a>
                            <p class="card-text">
                                Curabitur ac mi sit amet diam luctus porta. Phasellus pulvinar sagittis diam, et scelerisque ipsum lobortis nec.
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5" id="brands">
    <div class="container my-4">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1 fw-semibold text-decoration-underline">Marcas Parceiras</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod Lorem ipsum dolor sit amet.</p>
            </div>
            <div class="col-lg-9 m-auto">
                <div class="row d-flex flex-row">
                    <div class="col">
                        <div class="pt-2 pt-md-0"">            
              <div class=" carousel-item active">
                            <div class="row">
                                <div class="col-3 p-md-5" data-aos="fade-right">
                                    <a href="#"><img class="img-fluid brand-img" src="assets/brand_01.png" alt="Brand Logo"></a>
                                </div>
                                <div class="col-3 p-md-5">
                                    <a href="#"><img class="img-fluid brand-img" src="assets/brand_02.png" alt="Brand Logo"></a>
                                </div>
                                <div class="col-3 p-md-5">
                                    <a href="#"><img class="img-fluid brand-img" src="assets/brand_03.png" alt="Brand Logo"></a>
                                </div>
                                <div class="col-3 p-md-5" data-aos="fade-left">
                                    <a href="#"><img class="img-fluid brand-img" src="assets/brand_04.png" alt="Brand Logo"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<!-------------------------------------------------------- CONTACT ---------------------------------------------------------------------------------------------->

<section class="py-5" style="background-color: #EFEFEF;" id="suport">
    <div class="container my-4">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1 fw-semibold text-decoration-underline">Suporte</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod Lorem ipsum dolor sit amet.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h2 class="fw-semibold text-decoration-underline">Visite a nossa loja</h2>
                <p>Nossa loja está localiza em São Paulo - SP</p>
                <p>Rua Santa Cristina 937 - Parque Residencial Santa Maria - 14406-552</p>
                <h2 class="fw-semibold text-decoration-underline">Ligue para nós</h2>
                <p>Entre em contato por estes telefone:</p>
                <p>(11) 4732-7883 / (11) 99943-9205</p>
            </div>
            <div class="col-md-6 ">
                <form method="GET" action="contact.php">
                    <div class="mb-3">

                        <input type="email" name="email" class="form-control" id="exampleFormControlInput1" placeholder="Digite seu email *">
                    </div>
                    <div class="mb-3">

                        <input type="text" name="nome" class="form-control" id="exampleFormControlInput1" placeholder="Digite seu nome *">
                    </div>
                    <select class="form-select mb-3 mt-4" aria-label="Default select example">
                        <option selected>Qual é o motivo do contato</option>
                        <option value="1">Reclamação</option>
                        <option value="2">Elogio</option>
                        <option value="3">Outros</option>
                    </select>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label"></label>
                        <textarea class="form-control" placeholder="Digite sua mensagem *" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-dark w-50">Enviar</button>

                </form>
            </div>
        </div>
    </div>
</section>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<script>
    AOS.init();
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<script>
    const myCarouselElement = document.querySelector('#myCarousel')
    const carousel = new bootstrap.Carousel(myCarouselElement, {
        interval: 1000,
        wrap: false
    })
    $('body').scrollspy({
        target: '#navbar-example'
    })
</script>