<div class="container-fluid h-100">
    <div class="row form-cadastro justify-content-center p-4">
        <div class="col-md-3 align-self-center mt-5">

            <div class="row justify-content-center mb-4">
                <h1 class="fw-semibold text-center">Sapatito</h1>
            </div>

            <form action="">
                <div class="input-group mt-2">
                    <input type="text" class="form-control bg-light btn-outline-secondary" placeholder="Nome completo">
                </div>
                <div class="input-group mt-2">
                    <input type="text" class="form-control bg-light btn-outline-secondary" placeholder="Email">
                </div>
                <div class="input-group mt-2">
                    <input type="text" class="form-control bg-light btn-outline-secondary" placeholder="Login">
                </div>
                <div class="input-group mt-2">
                    <input type="password" class="form-control bg-light btn-outline-secondary" placeholder="******">
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-info mt-2 form-control">Limpar</button>
                    </div>
                    <div class="col-md-12">
                        <button type="button" class="btn btn-success mt-2 form-control">Cadastrar</button>
                    </div>
                </div>
            </form>

            
            <div class="row justify-content-center mb-4">
                <a class="text-center">Já possui uma conta ?</a>
            </div>

            

        </div>
    </div>
</div>